# Generated by Django 4.0.4 on 2022-07-10 10:41

from django.db import migrations, models
import django.db.models.deletion
import libraryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_requestbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='issuebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateField(auto_now=True)),
                ('expirydate', models.DateField(default=libraryapp.models.get_expiry)),
                ('reqbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.requestbook')),
            ],
        ),
    ]
