# Generated by Django 4.0.4 on 2022-07-10 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0007_issuebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='reqbook',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book'),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
