# Generated by Django 4.1.1 on 2022-10-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_alter_usermember_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='issuedays',
            field=models.IntegerField(default=1),
        ),
    ]
