# Generated by Django 4.1.1 on 2022-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_alter_requestbook_issuedays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='issuedays',
            field=models.IntegerField(default=15),
        ),
    ]
